# Python on Linux Web App
# Build a Python project (using Django/Flask/Bottle frameworks) and deploy it to Azure as a Linux web app.
name: Deploy fastAPI to Azure Web App
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "backend/**"
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
# See this in-depth article on CI for Python applications: https://azure.github.io/AppService/2020/12/11/cicd-for-python-apps.html
#
# 1. Set up the following secrets in your repository:
#   AZURE_CREDENTIALS
#
# 2. Change these variables for your configuration:
env:
  AZURE_WEBAPP_NAME: calcifer # set this to your application's name
  WORKING_DIRECTORY: "backend" # set this to the path to your path of working directory inside github repository, defaults to the repository root
  PYTHON_VERSION: "3.10"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # checkout the repo
      - uses: actions/checkout@main
      # setup python
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # install dependencies
      - name: python install
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          sudo apt install python${{ env.PYTHON_VERSION }}-venv
          python -m venv prodenv
          source prodenv/bin/activate
          pip install setuptools
          pip install -r requirements.txt
      # Azure login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          mask-inputs: false
          general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
      # deploy web app
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C9C5C4E3E3A34DDFB4565CF00B25B992 }}
          package: ${{ env.WORKING_DIRECTORY }}
      # Azure logout
      - name: logout
        run: |
          az logout
